// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGZYaY389ubsOXQ_MtBwcj4b32eB0odRI',
    appId: '1:272719422079:web:debfedacd0fa039d13d54a',
    messagingSenderId: '272719422079',
    projectId: 'iot-dc274',
    authDomain: 'iot-dc274.firebaseapp.com',
    databaseURL: 'https://iot-dc274-default-rtdb.firebaseio.com',
    storageBucket: 'iot-dc274.firebasestorage.app',
    measurementId: 'G-80YT4PLS0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8uIHLSWJb9uzgHCW1nCLApS_qkfDYECQ',
    appId: '1:272719422079:android:f4d96771c80349b313d54a',
    messagingSenderId: '272719422079',
    projectId: 'iot-dc274',
    databaseURL: 'https://iot-dc274-default-rtdb.firebaseio.com',
    storageBucket: 'iot-dc274.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz2bYhJ1ID-7Ct0q_M3r36qHzxg8s3y80',
    appId: '1:272719422079:ios:75c4046f93807f1413d54a',
    messagingSenderId: '272719422079',
    projectId: 'iot-dc274',
    databaseURL: 'https://iot-dc274-default-rtdb.firebaseio.com',
    storageBucket: 'iot-dc274.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz2bYhJ1ID-7Ct0q_M3r36qHzxg8s3y80',
    appId: '1:272719422079:ios:75c4046f93807f1413d54a',
    messagingSenderId: '272719422079',
    projectId: 'iot-dc274',
    databaseURL: 'https://iot-dc274-default-rtdb.firebaseio.com',
    storageBucket: 'iot-dc274.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGZYaY389ubsOXQ_MtBwcj4b32eB0odRI',
    appId: '1:272719422079:web:b0a5ec20285405fe13d54a',
    messagingSenderId: '272719422079',
    projectId: 'iot-dc274',
    authDomain: 'iot-dc274.firebaseapp.com',
    databaseURL: 'https://iot-dc274-default-rtdb.firebaseio.com',
    storageBucket: 'iot-dc274.firebasestorage.app',
    measurementId: 'G-10Y50BZBF3',
  );
}
